apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysql-pv-claim
  namespace: database 
spec:
  storageClassName: {{.values.database.volume.storageClassName}}
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 20Gi